baseURL = "www.example.com"
languageCode = "en-us"
title = "Curtin Association of Medical Students"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_call_box = true
    hide_view_all_services = false  # set to true to hide the View All Services button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/banner.png"
    desktop_height = "36px"
    alt = "CAMS"

  [params.homepage_meta_tags]
    meta_description = "The society for the students of Curtin University Medical School"
    meta_og_title = "Curtin Association of Medical Students"
    meta_og_type = "website"
    meta_og_url = "https://sabiqulhoque.me/"
    meta_og_image = "https://github.com/Sabicool"
    meta_og_description = "The society for the students of Curtin University Medical School"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Designed by <a class="Sabiqul Hoque" href="https://www.sabiqulhoque.me">Sabiqul Hoque</a>'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Events"
    url = "/events/"
      weight = 3

  [[menu.main]]
      name = "Committee"
      url = "/Committee/"
      weight = 2

  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 1

  [[menu.main]]
      name = "Contact Us"
      url = "/contact/"
      weight = 4

  [[menu.main]]
      name = "Join Us"
      url = "https://docs.google.com/forms/d/e/1FAIpQLSflNwIcEt372D0vGNeiFvYXZ_bHC7oCxdODwYyCJIHry2fwUw/viewform"
      weight = 4

  [[menu.main]]
      name = "Prospectus"
      url = "/prospectus.pdf/"
      weight = 4

  [[menu.main]]
    name = "Mental Health Corner"
    url = "/mental_health_corner/about/"
      weight = 5

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Contact"
    url = "/contact/"
      weight = 2
